# Generated by Django 2.0.8 on 2018-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'base_manager_name': 'objects', 'ordering': ('start_time', 'end_time'), 'verbose_name': 'occurrence', 'verbose_name_plural': 'occurrences'},
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.CharField(max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_es',
            field=models.CharField(max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_zh',
            field=models.CharField(max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_es',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_fr',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_zh',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='label_en',
            field=models.CharField(max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='label_es',
            field=models.CharField(max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='label_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='label_zh',
            field=models.CharField(max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_en',
            field=models.TextField(null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_es',
            field=models.TextField(null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_fr',
            field=models.TextField(null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_zh',
            field=models.TextField(null=True, verbose_name='note'),
        ),
    ]
